### ISSUE TITLE
[iOS] 회원가입 화면 - Model, View 연동

### ISSUE THREAD

**Issue by TTOzzi** [codesquad-member-2020/signup-6#18]
- [x] ViewController 의 View 를 커스텀 클래스로 만들기
- [x] 만든 커스텀 뷰에 textField 와 label 바인딩
- [x] View -> VC 는 Delegate 를 통해 이벤트 전달
- [x] Model -> VC 는 Notification 을 통해 결과 전달

**Comment by crongro** [comment]
4개 다 하셨으면 닫으셔도 될 듯~!

**Comment by TTOzzi** [comment]
커밋으로 이슈를 닫도록 해주었는데 아직 dev 브랜치에 머지를 안해서 안닫혔네요.
얼른 끝내고 머지하도록 하겠습니다! 감사합니다.
